YSoftSoftware.WebUI/Controllers/AccountingProgramController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YSoftSoftware.Data.Abstract;
using YSoftSoftware.Entity;

namespace YSoftSoftware.WebUI.Controllers
{
    public class AccountingProgramController : Controller
    {
        private IAccountingProgramRepository repository;

        public AccountingProgramController(IAccountingProgramRepository _repository)
        {
            repository = _repository;
        }
        public IActionResult Index()
        {
            return View(repository.GetAll());
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(AccountingProgram entity)
        {
            if (ModelState.IsValid)
            {
                repository.Add(entity);
                repository.Save();

                return RedirectToAction("Index");
            }

            return View(entity);
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            return View(repository.GetById(id));
        }
        [HttpPost]
        public IActionResult Edit(AccountingProgram entity)
        {
            if (ModelState.IsValid)
            {
                repository.Update(entity);
                repository.Save();

                return RedirectToAction("Index");
            }

            return View(entity);
        }

        public IActionResult Delete(int id)
        {
            repository.Delete(id);
            repository.Save();
            return RedirectToAction("Index");
        }
    }
}

YSoftSoftware.WebUI/Controllers/PersonelController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using YSoftSoftware.Data.Abstract;
using YSoftSoftware.Entity;
using YSoftSoftware.WebUI.Models;

namespace YSoftSoftware.WebUI.Controllers
{
    public class PersonelController : Controller
    {
        private IUnitOfWork unitOfWork;
        public PersonelController(IUnitOfWork _unitOfWork)
        {
            unitOfWork = _unitOfWork;
        }
        public IActionResult Index()
        {
            return View(unitOfWork.Personels.GetAll().Where(p=>p.Status));
        }

        public IActionResult Create()
        {
            ViewBag.Program = new SelectList(unitOfWork.Programs.GetAll(), "AccountingProgramId", "Name");
            ViewBag.Department = new SelectList(unitOfWork.Departments.GetAll(), "DepartmentId", "DepartmentName");
            return View();
        }
        [HttpPost]
        public IActionResult Create(Personel personel)
        {
            if (ModelState.IsValid)
            {
                unitOfWork.Personels.Add(personel);
                unitOfWork.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(personel);
        }

        public IActionResult Edit(int id)
        {
            ViewBag.Program = new SelectList(unitOfWork.Programs.GetAll(), "AccountingProgramId", "Name");
            ViewBag.Department = new SelectList(unitOfWork.Departments.GetAll(), "DepartmentId", "DepartmentName");
            return View(unitOfWork.Personels.GetById(id));
        }
        [HttpPost]
        public IActionResult Edit(Personel personel)
        {
            if (ModelState.IsValid)
            {
                unitOfWork.Personels.Update(personel);
                unitOfWork.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(personel);
        }

        public IActionResult Delete(int Id)
        {
            unitOfWork.Personels.Delete(Id);
            unitOfWork.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            return View(unitOfWork.Personels.GetById(id));
        }

        public IActionResult Dismiss(int personelId)
        {
            unitOfWork.Personels.Dismiss(personelId);
            var personel = unitOfWork.Personels.GetById(personelId);

            unitOfWork.Compensations.Add(personelId, CompensationCalculate.Calculate(personel));
            unitOfWork.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult GetDismiss()
        {
            return View(unitOfWork.Compensations.GetAll());
        }
    }
}

YSoftSoftware.WebUI/Controllers/ProjectController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using YSoftSoftware.Data.Abstract;
using YSoftSoftware.Entity;

namespace YSoftSoftware.WebUI.Controllers
{
    public class ProjectController : Controller
    {
        private IUnitOfWork unitOfWork;
        public ProjectController(IUnitOfWork _unitOfWork)
        {
            unitOfWork = _unitOfWork;
        }

        public IActionResult Index()
        {
            return View(unitOfWork.Projects.GetAll());
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Manager = new SelectList(unitOfWork.Personels.GetByDepartment("Manager").Where(p => p.Status), "PersonelId", "Name");
            ViewBag.Programmer = unitOfWork.Personels.GetByDepartment("Programmer").Where(p=>p.Status).ToList();
            ViewBag.Designer = unitOfWork.Personels.GetByDepartment("Designer").Where(p => p.Status).ToList();
            ViewBag.Analyst = unitOfWork.Personels.GetByDepartment("Analyst").Where(p => p.Status).ToList();
            return View();
        }
        [HttpPost]
        public IActionResult Create(Project project, int[] Personel)
        {
            if (ModelState.IsValid)
            {
                project.Personels = unitOfWork.Personels.GetByIds(Personel);

                unitOfWork.Projects.Add(project);
                unitOfWork.Projects.Save();
                return RedirectToAction("Index");
            }

            return Create();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Manager = new SelectList(unitOfWork.Personels.GetByDepartment("Manager").Where(p => p.Status), "PersonelId", "Name");
            ViewBag.Programmer = unitOfWork.Personels.GetByDepartment("Programmer").Where(p => p.Status).ToList();
            ViewBag.Designer = unitOfWork.Personels.GetByDepartment("Designer").Where(p => p.Status).ToList();
            ViewBag.Analyst = unitOfWork.Personels.GetByDepartment("Analyst").Where(p => p.Status).ToList();
            return View(unitOfWork.Projects.GetById(id));
        }
        [HttpPost]
        public IActionResult Edit(Project project, int[] Personel)
        {
            if (ModelState.IsValid)
            {
                project.Personels = unitOfWork.Personels.GetByIds(Personel);

                unitOfWork.Projects.Update(project);
                unitOfWork.Projects.Save();
                return RedirectToAction("Index");
            }

            return View(project);
        }

        public IActionResult Details(int id)
        {
            ViewBag.Manager = unitOfWork.Personels.GetByDepartmentAndProject("Manager", id).ToList();
            ViewBag.Programmer = unitOfWork.Personels.GetByDepartmentAndProject("Programmer", id).ToList();
            ViewBag.Designer = unitOfWork.Personels.GetByDepartmentAndProject("Designer", id).ToList();
            ViewBag.Analyst = unitOfWork.Personels.GetByDepartmentAndProject("Analyst", id).ToList();
            return View(unitOfWork.Projects.GetById(id));
        }

        public IActionResult Search(string q)
        {
            return View("Index",unitOfWork.Projects.SearchProject(q));
        }

        public IActionResult Delete(int id)
        {
            unitOfWork.Projects.Delete(id);

            return RedirectToAction("Index");
        }

    }
}

YSoftSoftware.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>

    <title>@ViewData["Title"] - YSoftSoftware</title>


    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    <header>
        @Html.Partial("_navbar")
    </header>

    <div class="container mt-4">
        @RenderBody()
    </div>


    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

    @await RenderSectionAsync("Scripts", required: false)


</body>
</html>

YSoftSoftware.WebUI/Views/Shared/_navbar.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" asp-controller="Project" asp-action="Index">Projects <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Company
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" asp-controller="Personel" asp-action="Index">Employee</a>
                    <a class="dropdown-item" asp-controller="AccountingProgram" asp-action="Index">Programs</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" asp-controller="Personel" asp-action="GetDismiss">Quit Job</a>
                </div>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" asp-controller="Project" asp-action="Search">
            <input class="form-control mr-sm-2" name="q" id="q" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

YSoftSoftware.WebUI/Views/Shared/_projects.cshtml
@model IEnumerable<Project>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Project ID</th>
            <th>Project Name</th>
            <th>Status</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.ProjectId</td>
                <td>@item.ProjectName</td>
                <td>
                    @if (item.Status)
                    {
                        <i class="fas fa-check-circle"></i>
                    }
                    else
                    {
                        <i class="fas fa-times-circle"></i>
                    }
                </td>
                <td>
                    <a asp-controller="Project" asp-action="Details" asp-route-id="@item.ProjectId" class="btn btn-primary btn-sm">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>